### ISSUE TITLE
Missing drawer controller

### ISSUE THREAD

**Issue by Gerold55** [minetest-mods/drawers#15]
This mod was released but it doesn't have a drawer controller and people are still finding bugs 😞

**Comment by LNJ2** [comment]
I have *NOT* released a final or finished version of this mod. The fact that I'm currently not working on this mod isn't implying that it is finished! If you had looked up the To-Dos in the readme, you would know that it is official that the drawer controller is not contained in this. I haven't said anywhere that this mod contains a drawer controller. This is voluntary work I and other people are doing in their freetime, you can't complain about not done work! :P

If you've got a problem with not having a drawer controller, then either contribute to this mod, create your personal fork or say something nice encouraging the development (even if this probably won't change my interests)!

That there are still bugs is normal and nothing special, but you can't expect that I have to fix them. I think some bugs are probably also caused by changes in MCL2 (correct my if you know more).

**Comment by Gerold55** [comment]
No the mod has been moved to mod releases in the forums so... 😕

**Comment by Gerold55** [comment]
I didn't mean any harm by anything. I was just wondering because of that.

**Comment by LNJ2** [comment]
Ok, sorry. I misunderstood you.

1.
