### ISSUE TITLE
Drawer Controllers are really buggy even with the new patch

### ISSUE THREAD

**Issue by sparky4** [minetest-mods/drawers#57]
I play on the LinuxForks server and we use the drawers mod on the server. an Issue is that even with the latest patch of the drawer controllers some drawer controllers work and some dont. the ones that dont work strangely reject input of items and fails to output items but it will accept items when the drawers are empty but it will not eject if there is a matching item in a drawer. again only some drawer controllers break while others work.

**Comment by erstazi** [comment]
Another thing to add to @sparky4's issue is that a server reboot resolves 99% of the drawer controllers but then over time, some drawer controllers fail again. This is limited to the drawer controllers from what I have seen.

**Comment by gpcf** [comment]
I think I solved this. The problem is that `drawers.drawer_visuals` is indexed with `minetest.serialize(pos)`, which is unsuitable for this purpose. See the following example (on luajit):

```
> minetest.serialize({x=141,y=13,z=11})
return {["y"]=13, ["x"]=141, ["z"]=11}

> minetest.serialize({y=13,x=141,z=11})
return {["x"]=141, ["y"]=13, ["z"]=11}
```
so the same position yields two different strings, and thus the indexing fails. Note that when inserting into the drawer for the first time, the position gets generated in {x,y,z} order and then serialized and stored in the node meta (and the string above is used as the index for `drawers.drawer_visuals`), where it is stored in the {y,x,z} order as shown in the example above. Then, this order is serialized into the string below, yielding a different string, so the indexing fails.

**Comment by gpcf** [comment]
a fix will follow shortly.
